### ISSUE TITLE
Support for Gemini,Groq,Ollama

### ISSUE THREAD

**Issue by syedazharmbnr1** [RamiAwar/dataline#242]
need to support to use gemini,groq and ollama models

**Comment by RamiAwar** [comment]
That's all going to come soon, we're holding off on doing it because some models (looking at you GPT 4o) perform really badly for some reason. So we don't want to just blindly release support for models. We wanna ensure they pass some basic QA.

So we built an eval pipeline, probably should be done next week. Then we can start supporting more models!
